#!/usr/bin/env php

<?php
/**
 * 控制台下命令行处理请求，命令行业代码统一放在 app\modules\console\目录下
 *
 * 命令  ./wen console/test 调用 app\modules\console\ConsoleController.test()方法
 * 命令  ./wen console/test city 调用 app\modules\console\ConsoleController.test('city')方法
 * 命令  ./wen console/test city,age 调用 app\modules\console\ConsoleController.test(['city','age'])方法, 数组参数以逗号组成
 */

if (version_compare($ver = PHP_VERSION, $req = '5.4.0', '<')) {
    exit(sprintf('You are running PHP %s, but system needs at least <strong>PHP %s</strong> to run.', $ver, $req));
}

//目录分隔符
define('DS', DIRECTORY_SEPARATOR);

//根路径
define('ROOT', dirname(__FILE__));

//框架内核路径
define('APP_ROOT', ROOT . DS . 'app');

//根日志目录路径
define('LOG_ROOT', ROOT . DS . 'tmp'. DS .'logs');

//是否开启debug模式，开发环境设置为1，正式环境设置为0
define('DEBUG', 1);


if (DEBUG) {
    error_reporting(E_ALL^E_NOTICE);
    ini_set('display_errors', true);
} else {
    ini_set('display_errors', false); 
}

// 设置时区，合法时区设置参看 http://php.net/manual/en/timezones.php
date_default_timezone_set('Asia/Chongqing');

//自动加载类文件，遵循PHP-FIG PSR-4规范
spl_autoload_register(function($className){
    $fileName = ucwords(substr($className, strrpos($className, '\\') + 1)) . '.php';
    $filePath = ROOT . DS . str_replace('\\', DS, substr($className, 0, strrpos($className, '\\'))) . DS . $fileName;
    
    if (file_exists($filePath)) {
        require_once $filePath;
    }
});

//使用 Composer autoloader
if(file_exists(APP_ROOT . DS . 'vendor'. DS .'autoload.php')) {
	require_once APP_ROOT . DS . 'vendor'. DS .'autoload.php';
}

use app\core\base\Wen;

//走你！
Wen::createConsoleApplication()->run($argv);